name: Generate Snake Contribution Graph

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1 - Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2 - Generate the snake animation
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: vinayakmishra4
          outputs: dist/snake.svg

      # Step 3 - Push the changes back to the repo
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
